use test;

-- SUPPRESION D'UN ENREGISTREMENT : DELETE

DELETE FROM fdps WHERE nom_fdp = "Allo";

-- SUPPRESSION DE PLUSIEURS ENREGISTREMENT

DELETE FROM fdps WHERE id_fdps = 1 OR id_fdps = 4;

-- SUPPRIME LES DONNEES D'UNE TABLE EN REINITIALISANT LES CLES PRIMAIRES

TRUNCATE fdps;